### ISSUE TITLE
Have an alternative to buildGraph() as loadGraph() that would take a JSON URL

### ISSUE THREAD

**Issue by Utopiah** [cjroth/aframe-d3-3d-graph-example#1]
Being able to build a random graph is nice but it's rarely needed. On the other hand it is very convenient to pass as URL a JSON file representing a graph.

Could be assigned from a component property value then called during init().

**Comment by cjroth** [comment]
Hey I agree but this is just an example to show how this stuff fits together. In the wild I would do the same.

**Comment by Utopiah** [comment]
It's too late, it's already in production for a critical application with billions of users. Please don't take a harsh decision! ;)

**Comment by cjroth** [comment]
Haha funny joke

**Comment by cjroth** [comment]
Send a PR though if you desire.
